#!/usr/bin/env bash
# uploads a file from local machine  to a server
message="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
path_to_file=$1
server_ip=$2
username=$3
path_to_ssh_key=$4
if [ "$4" ]; then
   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
     scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$message";
fi
