#!/usr/bin/env bash
# Update package index
sudo apt-get update

# Install Nginx
sudo apt-get install nginx -y

# Configure Nginx to listen on port 80
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default

# Restart Nginx
sudo /etc/init.d/nginx restart

# Create index.html file with "Hello World!" content
echo "Hello World!" | sudo tee /var/www/html/index.html

# Verify that Nginx is serving the expected content
curl http://localhost/
