#!/usr/bin/env bash
# Install nginx on your web-01
sudo apt-get update
sudo apt-get install nginx -y
sudo sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
sudo /etc/init.d/nginx restart
echo "Hello World!" | sudo tee /var/www/html/index.html
curl http://localhost/
