#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page
sudo apt-get update -y
sudo apt-get -y install nginx
sudo chown -R "$USER":"$USER" /var/www/
sudo chown -R "$USER":"$USER" /etc/nginx
echo "Hello World!" >/var/www/html/index.html
sudo sed -i "/servr_name _;/a \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=CevxZvSJLk8 permanent;" /etc/nginx/sites-available/default
sudo systemctl restart nginx
