#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02
sudo apt-get update
sudo apt-get install -y nginx
touch /var/www/html/index.html
echo "Hello world" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a add_header X-server-By $HOSTNAME;"/etc/nginx/sites-available/default
service nginx restart
