#!/usr/bin/env bash
# displaying number from 1-100 using while loop and 
# Displays Fizz when the number is multiple of 3
# Displays Buzz when the number is a multiple of 5
# Displays FizzBuzz when the number is a multiple of 3 and 5 
# other wises displays numbers
i=1
while (( i<=100))
do
    if [[ $i%3 -eq 0 ]] && [[ $i%5 -eq 0 ]]
    then
        echo "FizzBuzz"
    elif (( i%3==0 ))
    then
        echo "Fizz"
    elif (( i%5==0 ))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
    i=$((i+1))
done
