#!/usr/bin/env bash
# displaying "Best School" 10 times using while loop and if
# and if i=9; prints hi in new line
i=1
while (( i<=10));
do
    echo "Best School"
    if (( i == 9))
    then
        echo "hi"
    fi
    i=$((i+1))
done
