#!/usr/bin/env bash
# displaying "Best School" 10 times using while loop and if
# elif and else and if i=4; prints bad luck and if i=8 
# prints good luck
i=1
while (( i<=10));
do
    if (( i==4 ))
    then
        echo "bad luck"
    elif (( i==8 ))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    i=$((i+1))
done
