#!/usr/bin/env bash
# displaying numbers from 1-20 using while loop and 
# if i = 4 prints bad luck from China
# if i = 9 prints bad luck from Japan
# if i = 17 prints bad luck from Italy
i=1
while (( i<=20 ));
do
    echo "$i"
    case $i in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((++i))
done
