#!/usr/bin/env bash
# displays The content of the current directory In a list format
# Where only the part of the name after the first dash is displayed 
dir_content=0
command=$(ls)
for dir_content in $command
do
    echo "$dir_content" | cut -d "-" -f2
done
