#!/usr/bin/env bash
# this script  gives information about the school file
file=./school
if [ -e "$file" ] || [ -d "$file" ]
then
    echo "school file exists"
    if [ -s  "$file" ]
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi
    if [ -f "$file" ]
    then
	echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi
