#!/usr/bin/env bash
# running Nginx as the nginx user, listening on all active IPs on port 8080
sudo service nginx stop
sudo sed -i 's/user www-data/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80 default_server/listen 8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx start
